#ifndef _SERVEREVENTSMANAGER_H_
#define _SERVEREVENTSMANAGER_H_

#include "../../common/models/BlockingQueue.h"
#include "../Server.h" 

//Works with events generated by server (game) and received from players

class ServerEventsManager {
    private:
        Server *serverOwn_;
        BlockingQueue* eventsQueue_;


    public:
        ServerEventsManager();
        ~ServerEventsManager();
};

#endif