#ifndef _SERVEREVENTSMANAGER_H_
#define _SERVEREVENTSMANAGER_H_

#include "../../common/models/BlockingQueue.h"
#include "../../common/models/messages/Message.h"
#include "../Server.h"
#include "../../common/models/events/Event.h"

//Works with events generated by server (game) and received from players
class Server;

class ServerEventsManager {
    private:
        Server *serverOwn_;
        BlockingQueue<Message*>* eventsQueue_;


    public:
        ServerEventsManager(Server *server);
        ~ServerEventsManager();

        void process(Event *event);

        void processingCycle();
};

#endif